import 'package:final_cv/Models/course_info_model.dart';

List<Course> dummyCourses = [
  Course(
    courseCode: 'MA517',
    courseTitle: 'Distributed Algorithms',
    academicYear: '2023-24',
    instructorName: 'Kaushik Mondal',
    instructorUid: "--",
    image: 'assets/mathematics.jpg',
    isCheckingAttendance: false,
    courseReferenceId: 'asdfljak',
  ),
  Course(
    courseCode: 'MA302',
    courseTitle: 'Optimization Techniques',
    academicYear: '2023-24',
    instructorName: 'Arti Pandey',
    instructorUid: "--",
    image: 'assets/physics.jpg',
    isCheckingAttendance: false,
    courseReferenceId: 'asdfljak',
  ),
  Course(
    courseCode: 'HS301',
    courseTitle: 'Operation Management',
    academicYear: '2023-24',
    instructorName: 'Ravi Kumar',
    instructorUid: "--",
    image: 'assets/chemistry.jpg',
    isCheckingAttendance: false,
    courseReferenceId: 'asdfljak',
  ),
  Course(
    courseCode: 'CS503',
    courseTitle: 'Machine Learning',
    academicYear: '2023-24',
    instructorName: 'Shashi Shekhar Jha',
    instructorUid: "--",
    image: 'assets/biology.jpg',
    isCheckingAttendance: false,
    courseReferenceId: 'asdfljak',
  ),
  Course(
    courseCode: 'CS204',
    courseTitle: 'Computer Architecture',
    academicYear: '2023-24',
    instructorName: 'Neeraj Goel',
    instructorUid: "--",
    isCheckingAttendance: false,
    image: 'assets/history.jpg',
    courseReferenceId: 'asdfljak',
  ),
];
